version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: "true"
    volumes:
      - sqlite_data:/rails/storage
      - ./public:/rails/public
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:prepare && bundle exec rails db:seed && bundle exec rails server -b 0.0.0.0"

volumes:
  sqlite_data: